[build]
  functions = "netlify/functions"

[[redirects]]
  from = "/api/views"
  to = "/.netlify/functions/views"
  status = 200

[[redirects]]
  from = "/api/track"
  to = "/.netlify/functions/track"
  status = 200

[[redirects]]
  from = "/api/analytics"
  to = "/.netlify/functions/analytics"
  status = 200

[[redirects]]
  from = "/api/admin-login"
  to = "/.netlify/functions/admin-login"
  status = 200

[[redirects]]
  from = "/api/admin-logout"
  to = "/.netlify/functions/admin-logout"
  status = 200

[[redirects]]
  from = "/api/admin-items"
  to = "/.netlify/functions/admin-items"
  status = 200

[[redirects]]
  from = "/api/items"
  to = "/.netlify/functions/items"
  status = 200

[[redirects]]
  from = "/admin.html"
  to = "/public/admin.html"
  status = 200

[[redirects]]
  from = "/analytics.html"
  to = "/public/analytics.html"
  status = 200
